name: cargo build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry + index + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install Dependencies
        run: |
            sudo apt-get update && \
            sudo apt-get install -y \
            build-essential \
            clang \
            curl \
            libssl-dev \
            protobuf-compiler

      - name: Set up Rust from rust-toolchain.toml
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.84.1"
          override: true
          components: rustfmt, clippy, rust-src
          target: wasm32-unknown-unknown

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Build (release)
        run: cargo build --release 
        timeout-minutes: 90
